apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - canary-deployment.yaml
  - canary-service.yaml

# En prod : 3 r√©plicas, ressources maximales
patches:
  - target:
      kind: Deployment
      name: turbofan-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
