apiVersion: v1
kind: ConfigMap
metadata:
  name: turbofan-config
  labels:
    app: turbofan-api
data:
  MLFLOW_TRACKING_URI: "http://mlflow-svc:5000"
  MODEL_NAME: "turbofan_rul_predictor"
  MODEL_STAGE: "Production"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
