apiVersion: v1
kind: Service
metadata:
  name: turbofan-api-svc
  labels:
    app: turbofan-api
spec:
  type: ClusterIP
  selector:
    app: turbofan-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
